#!/usr/bin/env bash

if [ "$#" -lt 4 ]; then
	echo "Usage: bash runlarge_vary_n.sh min max inc runs"
	echo "Usage: bash runlarge_vary_n.sh 0 100 10 50"
	exit 1
fi

MIN=$1
MAX=$2
INC=$3
RUNS=$4

PLACEMENT_ARRAY=(RANDOM_CIRCLE GRID_CIRCLE BORDER_CIRCLE)
PLACEMENT_RADIUS_ARRAY=(500 750)

if [ "$#" -gt 4 ]; then
	PLACEMENT_ARRAY=($5)
fi
if [ "$#" -gt 5 ]; then
	PLACEMENT_RADIUS_ARRAY=($6)
fi

LOCAL_BEHAVIORS=(
FACE_EAST
GENETIC_astnm01
GENETIC_astnm02
GENETIC_astnm03
GENETIC_astnm04
GENETIC_astnm05
GENETIC_astnm06)

GLOBAL_BEHAVIORS=(
FACE
CIRCLE
RANDOM
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-0-FACE-0
POLYGON10)

GLOBAL_BEHAVIOR_500=(
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-750-CIRCLE-900
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-750-CIRCLE-750
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-900-CIRCLE-900)

GLOBAL_BEHAVIOR_750=(
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-900-CIRCLE-1100
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-900-CIRCLE-900
MULTIHERD-CIRCLE-MIN_AVG_DIR_NEIGH-1100-CIRCLE-1100)

for PLACEMENT_RADIUS in "${PLACEMENT_RADIUS_ARRAY[@]}"
do 
	for PLACEMENT in "${PLACEMENT_ARRAY[@]}"
	do
		for GLOBAL_BEHAVIOR in "${GLOBAL_BEHAVIORS[@]}"
		do
			for LOCAL_BEHAVIOR in "${LOCAL_BEHAVIORS[@]}"
			do
				echo "${PLACEMENT_RADIUS} ${PLACEMENT} ${GLOBAL_BEHAVIOR} ${LOCAL_BEHAVIOR}"
				bash scripts/run_herd_multistage_nomomentum.sh ${PLACEMENT} ${PLACEMENT_RADIUS} ${GLOBAL_BEHAVIOR} \
					${LOCAL_BEHAVIOR} $MIN $MAX $INC $RUNS
			done
		done
		if [ ${PLACEMENT_RADIUS} -eq "750" ]; then
			for GLOBAL_BEHAVIOR in "${GLOBAL_BEHAVIOR_750[@]}"
			do
				for LOCAL_BEHAVIOR in "${LOCAL_BEHAVIORS[@]}"
				do
					echo "${PLACEMENT_RADIUS} ${PLACEMENT} ${GLOBAL_BEHAVIOR} ${LOCAL_BEHAVIOR}"
					bash scripts/run_herd_multistage_nomomentum.sh ${PLACEMENT} ${PLACEMENT_RADIUS} ${GLOBAL_BEHAVIOR} \
						${LOCAL_BEHAVIOR} $MIN $MAX $INC $RUNS 
				done
			done
		fi
		if [ ${PLACEMENT_RADIUS} -eq "500" ]; then
			for GLOBAL_BEHAVIOR in "${GLOBAL_BEHAVIOR_500[@]}"
			do
				for LOCAL_BEHAVIOR in "${LOCAL_BEHAVIORS[@]}"
				do
					echo "${PLACEMENT_RADIUS} ${PLACEMENT} ${GLOBAL_BEHAVIOR} ${LOCAL_BEHAVIOR}"
					bash scripts/run_herd_multistage_nomomentum.sh ${PLACEMENT} ${PLACEMENT_RADIUS} ${GLOBAL_BEHAVIOR} \
						${LOCAL_BEHAVIOR} $MIN $MAX $INC $RUNS 
				done
			done
		fi
	done
done 
	
