#!/usr/bin/env bash

if [ "$#" -lt 5 ]; then
	echo "Usage: bash runconvergence_multilarge_all.sh \
	    min max inc runs numConvergence [PLACEMENT]"
	exit 1
fi

MIN=$1
MAX=$2
INC=$3
RUNS=$4
NUMCONVERGENCE=$5

PLACEMENTS=(RANDOM_RECT GRID_RECT K_MEANS)

if [ "$#" -eq 6 ]; then
    PLACEMENTS=($6)
fi

LOCAL_BEHAVIORS=(
FACE_EAST
OFFSET_MOMENTUM
ONE_STEP_LOOKAHEAD
COORDINATED
COUZIN
GENETIC_ast01
GENETIC_ast02
GENETIC_ast03
GENETIC_ast04
GENETIC_ast05
GENETIC_ast06
GENETIC_ast07)
ONE_STAGE_GLOBAL_BEHAVIORS=(
FACE
RANDOM)
MULTI_STAGE_GLOBAL_BEHAVIORS=(
MULTILARGE-150-MIN_AVG_DIR_NEIGH-
MULTILARGE-200-MIN_AVG_DIR_NEIGH-
MULTILARGEFIXED-150-MIN_AVG_DIR_NEIGH-
MULTILARGEFIXED-200-MIN_AVG_DIR_NEIGH-
MULTILARGELOCAL-150-MIN_AVG_DIR_NEIGH-
MULTILARGELOCAL-200-MIN_AVG_DIR_NEIGH-)

for GLOBAL_BEHAVIOR in "${ONE_STAGE_GLOBAL_BEHAVIORS[@]}"
do
	for LOCAL_BEHAVIOR in "${LOCAL_BEHAVIORS[@]}"
	do
		for PLACEMENT in "${PLACEMENTS[@]}"
		do
			echo "$PLACEMENT $GLOBAL_BEHAVIOR $LOCAL_BEHAVIOR"
	
			bash scripts/runconvergence_multilarge.sh $PLACEMENT $GLOBAL_BEHAVIOR $LOCAL_BEHAVIOR \
				$MIN $MAX $INC $RUNS $NUMCONVERGENCE
		done
	done
done

for MULTISTAGE_GLOBAL_BEHAVIOR in "${MULTI_STAGE_GLOBAL_BEHAVIORS[@]}"
do
	for LOCAL_BEHAVIOR in "${LOCAL_BEHAVIORS[@]}"
	do
		for PLACEMENT in "${PLACEMENTS[@]}"
		do
			GLOBAL_BEHAVIOR="${MULTISTAGE_GLOBAL_BEHAVIOR}${LOCAL_BEHAVIOR}"
			echo "$PLACEMENT $GLOBAL_BEHAVIOR $LOCAL_BEHAVIOR"
	
			bash scripts/runconvergence_multilarge.sh $PLACEMENT $GLOBAL_BEHAVIOR $LOCAL_BEHAVIOR \
				$MIN $MAX $INC $RUNS $NUMCONVERGENCE
		done
	done
done
